from django.urls import path, include
from rest_framework.routers import DefaultRouter # utility that automatically generates URL routes for a ViewSet (a class-based view that handles CRUD logic for a model)
from .views import NotesViewSet, RegisterView

router = DefaultRouter()
router.register('notes', NotesViewSet, basename='notes')

urlpatterns = [
    path('', include(router.urls)), #Includes all the URLs generated by the router into the app’s urlpatterns.
    path('register/', RegisterView.as_view(), name='register'),
]
